### ISSUE TITLE
Working with react-toolbox

### ISSUE THREAD

**Issue by kockok** [brunch/postcss-brunch#44] opened 2017-04-14 11:42 UTC
I've spent days to integrate brunch with react-toolbox, still struggling.

Here's the setup:
package.json:
```
  "dependencies": {
    "react": "^15.5",
    "react-dom": "^15.5",
    "react-redux": "~5.0.4",
    "react-toolbox": "^2.0.0-beta.8",
    "redux": "~3.6.0",
    "redux-observable": "^0.14.1",
    "rxjs": "^5.3.0"
  },
  "devDependencies": {
    "brunch": "^2",
    "postcss-brunch": "^2.0.5",
    "sass-brunch": "^2.10.4",
    "clean-css-brunch": "^2",
    "csswring": "^5.1",
    "auto-reload-brunch": "^2",
    "autoprefixer": "^6.7",
    "babel-brunch": "~6.1.1",
    "babel-preset-latest": "^6",
    "babel-preset-react": "~6.24",
    "hmr-brunch": "^0.1",
    "uglify-js-brunch": "^2"
  }
```
brunch config:
```
exports.files = {
  javascripts: {
    joinTo: 'app.js'
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: { presets: ['latest', 'react'] },
  postcss: {
    modules: true,
    processors: [
      require('autoprefixer')(['last 8 versions']),
      require('csswring')()
    ]
  }
};

exports.hot = true;
```
The error:
![screen shot 2017-04-14 at 7 42 05 pm](https://cloud.githubusercontent.com/assets/232541/25042421/7bbb5d58-214a-11e7-9c7f-30cfa910e5bd.png)

Please have a look.

**Comment by akhnaz** [comment] 2017-07-27 04:32
Hi, i also face the same problem. maybe because of different postcss version?

**Comment by kockok** [comment] 2017-07-28 03:02
Seems that they just ditched the development of brunch, and I reluctantly switched to webpack, poor.

**Comment by akhnaz** [comment] 2017-07-28 05:33
Hmm, so sad. Webpack is too much. Btw, i also try with Mozilla neutrino, but also got error with the css.

**Comment by shvaikalesh** [comment] 2017-07-29 19:13
Hello there. The issue is tracked in https://github.com/brunch/brunch/issues/1473. Should be fixed by https://github.com/brunch/brunch/pull/1664 when it is ready.

**Closed as completed** 2023-02-09 12:18 UTC
